### ISSUE TITLE
Entered text in searchbox disappears on focus.

### ISSUE THREAD

**Issue by aleks-linya** [drivas/jquery-multiselect#1]
As described in title if user enters something in searchbox and then selects options for instance (blur) then upon clicking again on searchbox (focus) text disappears.
I believe it's not user-friendly to clear user entered text on focus.

**Comment by aleks-linya** [comment]
I have created a pull request for this issue.
https://github.com/drivas/jquery-multiselect/pull/2

**Comment by drivas** [comment]
Merge pull #2
